@JoliPet_HostAddress = http://localhost:5007
@api = {{JoliPet_HostAddress}}/api

GET {{api}}/auth/guest-info
Accept: application/json

###
GET {{api}}/auth/whoami
Accept: application/json

###
POST {{api}}/auth/register
Content-Type: application/json

{
  "Username": "IvanTsiak",
  "Email": "ivantsiak@gmail.com",
  "Password": "good_password"
}

### 
POST {{api}}/auth/login
Content-Type: application/json

{
  "Email": "ivantsiak@gmail.com",
  "Password": "good_password"
}

###
GET {{api}}/Pets/types
Accept: application/json

###
POST {{api}}/Pets
Content-Type: application/json

{
  "TypeId": 1,
  "Name": "Сніжинка"
}

###
GET {{api}}/Pets/my
Accept: application/json

###
POST {{api}}/Interactions/talk
Content-Type: application/json

{
  "Message": "Бароко, ажурний, виграш, відважний, благий, білосніжний, безжурний, бездоганно, блиск"
}

###
POST {{api}}/Interactions/talk
Content-Type: application/json

{
  "Message": "Бідний, бідолашний біс боліти, бити, безславний"
}

###
GET {{api}}/Battles/targets
Accept: application/json

###
POST {{api}}/Battles/2/attack
Accept: application/json

###
POST {{api}}/Pets/abandon
Accept: application/json

###
GET {{api}}/Cemetery
Accept: application/json

###
GET {{api}}/Notifications
Accept: application/json

###
POST {{api}}/Notifications/3/read
Accept: application/json